services:
  redis:
    container_name: L1-redis
    image: redis:7-alpine
    user: root
    command: >
      sh -c 'mkdir -p /run/redis &&
             chmod 777 /run/redis &&
             exec redis-server --unixsocket /run/redis/redis.sock --unixsocketperm 777'
    volumes:
      - redis-socket:/run/redis
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -s /run/redis/redis.sock ping | grep PONG"]
      interval: 2s
      timeout: 1s
      retries: 15

  web_application:
    container_name: L1-web-application
    build: 
      context: .
      dockerfile: L1-web-application/Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      - HOST=${HOST}
      - PORT=${PORT}
      - SOCK=${SOCK}
      - DB_URL=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_db:5432/${POSTGRES_DB}
    volumes:
      - redis-socket:/run/redis
    depends_on:
      redis:
        condition: service_healthy

  stream_writer:
    container_name: L1-redis-stream_writer
    build: L1-redis-stream-writer/
    environment:
      - SOCK=${SOCK}
    volumes:
      - redis-socket:/run/redis
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  celery_worker:
    container_name: L1-celery-worker
    build: 
      context: .
      dockerfile: L1-celery-worker/Dockerfile
    environment:
      - SOCK=${SOCK}
      - EMAIL_USER=${EMAIL_USER}    
      - EMAIL_PASS=${EMAIL_PASS}    
      - DB_URL=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_db:5432/${POSTGRES_DB}
    volumes:
      - redis-socket:/run/redis
    depends_on:
      redis:
        condition: service_healthy

  postgres_db:
    container_name: L1-postgres-database
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  redis-socket:
  pgdata:
